export const GET_USERS_START = 'GET_USERS_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const CHECK_USER = "CHECK_USER";

export const FIND_USERS = "FIND_USERS";
export const FIND_USERS_START = "FIND_USERS_START";

export const LOAD_MORE_USERS_START = "LOAD_MORE_USERS_START";
export const LOAD_MORE_USERS_SUCCESS = "LOAD_MORE_USERS_SUCCESS";
export const LOAD_MORE_USERS_FAILURE = "LOAD_MORE_USERS_FAILURE";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
